require("custom.auto-source-configuration")
require("custom.keybinds")
require("custom.options")
require("custom.package-manager")
-- require("custom.default-to-file-manager")
require("custom.highlight-on-yank")
